<?php

require_once "apiTests.php";

/**
 * Test class for resource_data.
 * Generated by PHPUnit on 2011-12-02 at 16:58:03.
 */
class dataTests extends apiTests
{

    public function testGetRaces()
    {
        $data = $this->api->data->getRaces();
        $this->assertEquals("Human",$data->getNamebyId(1));
    }


    public function testGetClasses()
    {
        $data = $this->api->data->getClasses();
        $this->assertEquals("Hunter",$data->getNamebyId(0));
    }


    public function testGetGuildRewards()
    {
        $data = $this->api->data->getGuildRewards();
        $this->assertNotNull($data['rewards'][0]['achievement']['id']);
        $this->assertNotNull($data['rewards'][0]['achievement']['title']);
        $this->assertNotNull($data['rewards'][0]['achievement']['points']);
        $this->assertNotNull($data['rewards'][0]['achievement']['description']);
    }


    public function testGetGuildPerks()
    {
        $data = $this->api->data->getGuildPerks();
        $this->assertEquals($data['perks'][0]['guildLevel'],2);
    }


    public function testGetItemClasses()
    {
        $data = $this->api->data->getItemClasses();
        $this->assertEquals("Consumable",$data->getNamebyClass(0));
    }
}
?>
