<?php

require_once "apiTests.php";

/**
 * Test class for resource_data.
 * Generated by PHPUnit on 2011-12-02 at 16:58:03.
 */
class dataTests extends apiTests
{

    public function testGetRaces()
    {
        $data = $this->api->data->getRaces();
        $this->assertEquals($data['races'][0]['name'],"Human");
    }


    public function testGetClasses()
    {
        $data = $this->api->data->getClasses();
        $this->assertEquals($data['classes'][0]['name'],"Hunter");
    }


    public function testGetGuildRewards()
    {
        $data = $this->api->data->getGuildRewards();
        $this->assertEquals($data['rewards'][1]['achievement']['id'],4989);
    }


    public function testGetGuildPerks()
    {
        $data = $this->api->data->getGuildPerks();
        $this->assertEquals($data['perks'][0]['guildLevel'],2);
    }


    public function testGetItemClasses()
    {
        $data = $this->api->data->getItemClasses();
        $this->assertEquals($data['classes'][0]['name'],"Consumable");
    }
}
?>
